print(Nume Prenume      Grejdieru Andreea)
print(Adresa                 mun.Bălţi, str.Livădenilor 2  )
print(Telefon                +37378791708)
print(E-mail(s)              grejdieruandreea15@gmail.com)
print(Naţionalitatea	     moldoveanca)
print(Data naşterii	         23.08.2004)
print(Sex		             feminin)
print(Data                   2011-prezent)
print(Instituția             Instituția Publică Liceul Teoretic "Mihai Eminescu")
print(Limba maternă          română)
print(Alte limbi posedate    Engleza, rusa, germana)
print(Competenţe şi abilităţi sociale		 lucru în echipă,  amiabilitate, responsabilă, sociabilă, amabilă, comunicabilă)
print(Competenţe             Computer  Sisteme de Operare:   Windows)
print(Competenţe             Computer  Microsoft Office (Word, Excel, Power Point)  